### ISSUE TITLE
Photo retouching

### ISSUE THREAD

**Issue by PJaemin** [IDKiro/MCT#2]
Hello.
I wanna implement the algorithm on FiveK dataset, photo retouching.
How can I train the model?

**Comment by IDKiro** [comment]
For unpaired training, you only need to arrange the dataset and modify some hyperparameters according to the paper. Paired training is very simple, and please try it yourself.

**Comment by Maozhiquan** [comment]
您好，请问可以交流一下吗，我也想用这个来做人像图像修饰，我的vx：13628422019，如果大佬愿意和我交流，我会感激不尽的！！！

**Comment by Maozhiquan** [comment]
可以交流交流吗 这个做图像修饰效果咋样呀，真的很想和大佬交流，很想用这个算法
